version: 2
aliases:
  - &check-code-format
    name: Check code formatting
    command: yarn prettier --check

  - &restore-cache
    keys:
      - v2-dependencies-{{ .Branch }}-{{ checksum "package.json" }}
      - v2-dependencies-{{ .Branch }}
  - &save-node-cache
    key: v2-dependencies-{{ .Branch }}-{{ checksum "package.json" }}
    paths:
      - node_modules

  - &install-node-dependencies
    name: Install node dependencies
    command: yarn install --frozen-lockfile

defaults: &defaults
  working_directory: ~/website

jobs:
  check-formatting:
    <<: *defaults
    docker:
      - image: node:10
    resource_class: small
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run: *install-node-dependencies
      - run: *check-code-format
      - save_cache: *save-node-cache

  build-api-docs:
    working_directory: ~/website
    docker:
      - image: node:10
    resource_class: medium
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run: *install-node-dependencies
      - run:
          name: Build Daf
          command: yarn build:daf
      - run:
          name: Build Documentation
          command: yarn build:docs
      - run:
          name: Commit changes back to repo
          command: echo committing changes placeholder...

workflows:
  version: 2

  verify-build-local-docs:
    jobs:
      - check-formatting
      - build-api-docs:
          requires:
            - check-formatting
